export const CHANGE_FILTER = 'PARAMS/CHANGE_PARAMS_ALL';
export const GET_TICKETS_START = 'TICKETS/GET_TICKETS_START';
export const GET_TICKETS_END = 'TICKETS/GET_TICKETS_END';
export const GET_SEARCH_ID = 'TICKETS/GET_SEARCH_ID';
export const ERROR_SERVER = 'TICKETS/ERROR_SERVER';
export const OFF_LOADING = 'TICKETS/OFF_LOADING';
export const CHANGE_SORT_ID = 'TICKETS/CHANGE_SORT_ID';
