export const CHANGE_PARAMS_ALL = 'PARAMS/CHANGE_PARAMS_ALL';
export const CHANGE_PARAMS_NULL = 'PARAMS/CHANGE_PARAMS_NULL';
export const CHANGE_PARAMS_ONE = 'PARAMS/CHANGE_PARAMS_ONE';
export const CHANGE_PARAMS_TWO = 'PARAMS/CHANGE_PARAMS_TWO';
export const CHANGE_PARAMS_THREE = 'PARAMS/CHANGE_PARAMS_THREE';
export const CHOOSE_ALL_PARAMS = 'PARAMS/CHOOSE_ALL_PARAMS';
